# Specify here which heaters and chps should be added to the Energy Balance and
# in which network. If the network is 'flexible', the producer will be 'split up'
# and added to both networks, with the split-share based on where it is needed
# most.
heaters:
  - name: Solar thermal
    network: residential
    input: Solar thermal
    type: heater
  - name: Gas heater
    network: residential
    input: Network gas
    type: heater
  - name: Biomass heater
    network: residential
    input: Wood pellets
    type: heater
  - name: Waste heater
    network: residential
    input: Waste
    type: heater
  - name: Geothermal
    network: flexible
    input: Geothermal
    type: heater
  - name: Coal heater
    network: flexible
    input: Coal
    type: heater
  - name: Oil heater
    network: flexible
    input: Oil
    type: heater
  - name: Lignite heater
    network: industrial
    input: Lignite, peat
    type: heater
  - name: Coal gas heater
    network: industrial
    input: Coal gas
    type: heater
  # - name: Collective heat pump
  #   network: residential
  #   type:
  #   input:
